### ISSUE TITLE
NullPointerException NotificareReceiver

### ISSUE THREAD

**Issue by shayanzoro** [Notificare/notificare-push-lib-react-native#2]
This exception happens in **NotificareReceiver** when I first start the app, but not after the first time.

notificare-push-lib-react-native 1.2.0
Android 6.0
LG G4

```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'void re.notifica.reactnative.NotificareEventEmitter.sendEvent(java.lang.String, com.facebook.react.bridge.ReadableMap, java.lang.Boolean)' on a null object reference

Fatal Exception: java.lang.RuntimeException: Unable to start receiver re.notifica.reactnative.NotificareReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'void re.notifica.reactnative.NotificareEventEmitter.sendEvent(java.lang.String, com.facebook.react.bridge.ReadableMap, java.lang.Boolean)' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2750)
       at android.app.ActivityThread.access$1800(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1433)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5525)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

I debugged and realised that **NotificareEventEmitter.INSTANCE** is null, since the **NotificareModule** will be initialized after **NotificareReceiver.onRegistrationFinished**

**Comment by jjonthemix** [comment]
Hi shayanzoro,

Can you please submit this question to support@notifica.re and also add which account you have and the app you are testing it with. Thank you.

Regards,

**Comment by shayanzoro** [comment]
Thanks Joel, I sent the email
